### ISSUE TITLE
can not download json

### ISSUE THREAD

**Issue by Bryan-AA** [adxcreative/RICE#1]
the json filed
[test_frameid2gtbox_20079_426751.json](https://js-ad.a.yximgs.com/bs2/ad-material-video/test_frameid2gtbox_20079_426751.json%5D) : A dict, key is frame_id of testset, value is the bounding box labels.
can not be found

**Comment by Bryan-AA** [comment]
and i also can not send  Licensing Agreement by e-mail to [chenyiyi@kuaishou.com](mailto:chenyiyi@kuaishou.com)

**Comment by deepalchemist** [comment]
see https://github.com/deepalchemist/crossview-semantic-alignment

**Comment by deepalchemist** [comment]
see https://github.com/deepalchemist/crossview-semantic-alignment
